name: mymixx
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  spotify_sdk: ^2.3.1
  http: ^1.2.1
  external_app_launcher: ^4.0.0



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  animated_text_kit: ^4.2.2
  google_generative_ai: ^0.4.3


flutter:


  uses-material-design: true


  assets:
    - images/


